# This config file is an example of my default settings in `config.toml` file
# They can be different from yours, so make your editions if you need to
# Example from OpenAI: https://github.com/openai/codex/blob/main/docs/example-config.md

[mcp_servers]
[mcp_servers.chrome-devtools]
command = "npx"
args = [ "chrome-devtools-mcp@latest" ]

[mcp_servers.dart]
command = "dart"
args = [ "mcp-server", "--experimental-mcp-server" ]

[mcp_servers.context7-mcp]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@upstash/context7-mcp", "--key", "KEY" ]

[tui]
# Desktop notifications from the TUI: boolean or filtered list. Default: true
# Examples: false | ["agent-turn-complete", "approval-requested"]
notifications = true

[features]
# Enable web search tool. Usually I preffer that model can do work better
# Default: false
web_search_request = true

